Issue 28 figure out how to add circuit block diagrams to documentation (#57)
* Remove sphinx hdl diagrams package

* Add netlistsvg install to dockerfile

* Add yosys to Dockerfile

* Change TOC depth to 1

* Add gitignore for source docs directory

* Remove sphinx-hdlcontrib package and add conf.py directory to path for docs

* Add working block diagram implementation

* Remove .

* Add support for rtds-action

* Change to get

* Add rtds-action to dockerfile

* Remove rtds action

* Add generate_hdl_svgs to build docs step of precommit

* Remove proc and opt from yosys call

* Add back proc and clean

* Remove simulations section

* Add ci job to check formatting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,14 +20,17 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 2
+
       - name: Check if Dockerfile changed in last commit
         run: |
           echo "DOCKERFILE_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep -c Dockerfile)" >> $GITHUB_ENV
+
       - name: Docker meta
         id: docker_meta
         uses: crazy-max/ghaction-docker-meta@v1
         with:
           images: bensampson5/openhdl
+
       - name: Check if docker image already exists
         run: |
           echo '{"experimental": "enabled"}' > ~/.docker/config.json;
@@ -36,12 +39,15 @@ jobs:
           else
             echo "DOCKER_IMAGE_EXISTS=0" >> $GITHUB_ENV;
           fi;
+
       - name: Set up QEMU
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         uses: docker/setup-qemu-action@v1
+
       - name: Set up Docker Buildx
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         uses: docker/setup-buildx-action@v1
+
       - name: Cache Docker layers
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         uses: actions/cache@v2
@@ -50,12 +56,14 @@ jobs:
           key: ${{ runner.os }}-buildx-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-buildx-
+
       - name: Login to Docker Hub
         if: github.event_name != 'pull_request' && (env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main')
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
       - name: Build and push
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         id: docker_build
@@ -69,6 +77,7 @@ jobs:
           labels: ${{ steps.docker_meta.outputs.labels }}
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
+
       - name: Image digest
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         run: echo ${{ steps.docker_build.outputs.digest }}
@@ -80,27 +89,41 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+
       - name: Docker meta
         id: docker_meta
         uses: crazy-max/ghaction-docker-meta@v1
         with:
           images: bensampson5/openhdl
+
       - name: Setup GitHub environment
         run: |
           echo "DOCKER_RUN_PRECOMMIT=docker run --rm -v $(pwd):/code ${{ steps.docker_meta.outputs.tags }} /code/tools/precommit.py" >> $GITHUB_ENV;
           echo "FORMAT_ERRORS_FILENAME=format-errors.txt" >> $GITHUB_ENV;
+          echo "DOC_ERRORS_FILENAME=doc-errors.txt" >> $GITHUB_ENV;
+
       - name: Pull docker image
         run: docker pull ${{ steps.docker_meta.outputs.tags }}
+
       - name: Build and run tests
         run: ${{ env.DOCKER_RUN_PRECOMMIT }} --test
+
       - name: Check format
         run: |
           ${{ env.DOCKER_RUN_PRECOMMIT }} --format && \
           git diff HEAD | tee ${{ env.FORMAT_ERRORS_FILENAME }} && \
           git reset --hard HEAD && \
           if [ -s ${{ env.FORMAT_ERRORS_FILENAME }} ]; then \
-              echo "Format check failed. Please run './tools/precommit.py --format' locally then recommit and push changes to fix."; \
+              echo "Format check failed. Please run './tools/precommit.py --format' locally then commit and push changes to fix."; \
               exit 1; \
           fi
+
       - name: Build docs
-        run: ${{ env.DOCKER_RUN_PRECOMMIT }} --docs
+        run: |
+          ${{ env.DOCKER_RUN_PRECOMMIT }} --docs && \
+          git diff HEAD | tee ${{ env.DOC_ERRORS_FILENAME }} && \
+          git reset --hard HEAD && \
+          if [ -s ${{ env.DOC_ERRORS_FILENAME }} ]; then \
+              echo "Build docs failed. Please run './tools/precommit.py --docs' locally, resolve any errors if necessary, then commit and push changes to fix."; \
+              exit 1; \
+          fi
