issue-38-Add_format_check_ci_step (#51)
* Change openhdl step to build step

* Added test and docs jobs to ci.yml

* Add analyze step

* Add run OpenHDL tests step to test job

* Add comments to ci.yml

* Fix job dependency issue

* Add check for c++ cmake formatting

* Force formatting fail

* Add upload artifact is c++/cmake formatting fails

* Fix upload path

* Add check hdl formatting step

* Add *.pyc to gitignore

* Add flags param to format_hdl

* Add commit with bad formatting

* Update precommit

* More fixes to precommit

* change to check hdl formatting step

* Try to fix check HDL formatting

* Fix file naming issue

* Add cats

* Fix typo in precommit

* Attempted fix to precommit to run on github runner

* Remove cats

* Print out format-check-hdl.txt

* Throw error if format-check-hdl is not empty

* Add cat back to format-check-hdl

* Try adding tests

* Try using exit

* Try to change to relative path and add git reset --hard

* Change back to absolute path

* Add useful message to HDL formatting check failure

* Add escape

* Add string fix to print message

* Switch && around on hdl format check to get better alignment on if

* Single format step

* Attempt to fix reference issue

* Remove quoted format-errors.txt

* Change upload artifact back to format-errors.txt

* Another attempt to use env variable

* Try to exclusively use github env

* Change build and run step

* Change to tee

* Change to tee

* Move setup github environment below docker meta

* Try to use DOCKER_RUN_PRECOMMIT

* Change check_format to use DOCKER_RUN_PRECOMMIT

* Add upload artifact for build and test report

* Remove upload artifact

* Remove upload artifact

* Add running cmake

* Add build docs step

* Change precommit

* Update precommit

* Fix format issue with counter.sv

* Add docs implementation

* Force docs failure

* Throw exception of nonzero returncode

* Fix conf.py forced error

* Force test failure

* Undo forced test failure

* ci.yml comments

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,48 +3,46 @@ name: ci
 on:
   push:
     branches:
-      - '**'
+      - "**"
     tags:
-      - 'v*'
+      - "v*"
 
 jobs:
-  docker-build:
+  # This job builds and updates the docker images on the OpenHDL's Docker Hub. It will create and push a
+  # new image if any of the following conditions apply:
+  #   1. This is a new commit to the 'main' branch.
+  #   2. If a tag for this branch does not already exist on OpenHDL's Docker Hub.
+  #   3. If the Dockerfile in the top project directory changed in the most recent commit.
+  docker:
     runs-on: ubuntu-latest
     steps:
-      - 
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 2
-      - 
-        name: Check if Dockerfile changed in last commit
-        run: | 
-          echo "DOCKERFILE_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep -c Dockerfile)" >> $GITHUB_ENV       
-      - 
-        name: Docker meta
+      - name: Check if Dockerfile changed in last commit
+        run: |
+          echo "DOCKERFILE_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep -c Dockerfile)" >> $GITHUB_ENV
+      - name: Docker meta
         id: docker_meta
         uses: crazy-max/ghaction-docker-meta@v1
         with:
           images: bensampson5/openhdl
-      - 
-        name: Check if docker image already exists
-        run: | 
+      - name: Check if docker image already exists
+        run: |
           echo '{"experimental": "enabled"}' > ~/.docker/config.json;
           if [[ $(docker manifest inspect ${{ steps.docker_meta.outputs.tags }} 2>/dev/null) ]]; then
             echo "DOCKER_IMAGE_EXISTS=1" >> $GITHUB_ENV;
           else
             echo "DOCKER_IMAGE_EXISTS=0" >> $GITHUB_ENV;
           fi;
-      - 
-        name: Set up QEMU
+      - name: Set up QEMU
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         uses: docker/setup-qemu-action@v1
-      - 
-        name: Set up Docker Buildx
+      - name: Set up Docker Buildx
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         uses: docker/setup-buildx-action@v1
-      -
-        name: Cache Docker layers
+      - name: Cache Docker layers
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         uses: actions/cache@v2
         with:
@@ -52,15 +50,13 @@ jobs:
           key: ${{ runner.os }}-buildx-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-buildx-
-      - 
-        name: Login to Docker Hub
+      - name: Login to Docker Hub
         if: github.event_name != 'pull_request' && (env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main')
-        uses: docker/login-action@v1 
+        uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Build and push
+      - name: Build and push
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         id: docker_build
         uses: docker/build-push-action@v2
@@ -73,37 +69,38 @@ jobs:
           labels: ${{ steps.docker_meta.outputs.labels }}
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
-      -
-        name: Image digest
+      - name: Image digest
         if: env.DOCKERFILE_CHANGED == '1' || env.DOCKER_IMAGE_EXISTS == '0' || github.ref == 'refs/heads/main'
         run: echo ${{ steps.docker_build.outputs.digest }}
+
+  # This job runs all the OpenHDL builds, tests, and checks
   openhdl:
-    needs: [docker-build]
+    needs: [docker]
     runs-on: ubuntu-latest
     steps:
-      -
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v2
-      - 
-        name: Docker meta
+      - name: Docker meta
         id: docker_meta
         uses: crazy-max/ghaction-docker-meta@v1
         with:
           images: bensampson5/openhdl
-      - 
-        name: Pull docker image
+      - name: Setup GitHub environment
         run: |
-          docker pull ${{ steps.docker_meta.outputs.tags }}
-      - 
-        name: Build OpenHDL
+          echo "DOCKER_RUN_PRECOMMIT=docker run --rm -v $(pwd):/code ${{ steps.docker_meta.outputs.tags }} /code/tools/precommit.py" >> $GITHUB_ENV;
+          echo "FORMAT_ERRORS_FILENAME=format-errors.txt" >> $GITHUB_ENV;
+      - name: Pull docker image
+        run: docker pull ${{ steps.docker_meta.outputs.tags }}
+      - name: Build and run tests
+        run: ${{ env.DOCKER_RUN_PRECOMMIT }} --test
+      - name: Check format
         run: |
-          echo "rm -rf build \
-                && mkdir build \
-                && cd build \
-                && cmake -GNinja .. \
-                && ninja" > build.sh \
-          && docker run --rm -v $(pwd):/code -w /code ${{ steps.docker_meta.outputs.tags }} /bin/bash build.sh
-      -
-        name: Run OpenHDL tests
-        run: |
-          docker run --rm -v $(pwd):/code -w /code/build ${{ steps.docker_meta.outputs.tags }} ninja check
+          ${{ env.DOCKER_RUN_PRECOMMIT }} --format && \
+          git diff HEAD | tee ${{ env.FORMAT_ERRORS_FILENAME }} && \
+          git reset --hard HEAD && \
+          if [ -s ${{ env.FORMAT_ERRORS_FILENAME }} ]; then \
+              echo "Format check failed. Please run './tools/precommit.py --format' locally then recommit and push changes to fix."; \
+              exit 1; \
+          fi
+      - name: Build docs
+        run: ${{ env.DOCKER_RUN_PRECOMMIT }} --docs
