Switch && around on hdl format check to get better alignment on if

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -129,14 +129,14 @@ jobs:
       - 
         name: Check HDL formatting
         run: |
-          docker run --rm -v $(pwd):/code ${{ steps.docker_meta.outputs.tags }} /code/tools/precommit.py --format-hdl \
-          && git diff HEAD > format-check-hdl.txt \
-          && git reset --hard HEAD \
-          && if [ -s format-check-hdl.txt ]; then \
-                 echo "HDL formatting check failed (see below). Please run './tools/precommit.py --format-hdl' locally then recommit and push changes to fix."; \
-                 cat format-check-hdl.txt; \
-                 exit 1; \
-             fi
+          docker run --rm -v $(pwd):/code ${{ steps.docker_meta.outputs.tags }} /code/tools/precommit.py --format-hdl && \
+          git diff HEAD > format-check-hdl.txt && \
+          git reset --hard HEAD && \
+          if [ -s format-check-hdl.txt ]; then \
+              echo "HDL formatting check failed (see below). Please run './tools/precommit.py --format-hdl' locally then recommit and push changes to fix."; \
+              cat format-check-hdl.txt; \
+              exit 1; \
+          fi
       - 
         name: If previous step failed, upload artifact with HDL formatting issues.
         if: failure()
